//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediAI.Resources.Diagnoses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediAI.Resources.Diagnoses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence Level.
        /// </summary>
        public static string ConfidenceLevel {
            get {
                return ResourceManager.GetString("ConfidenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose Image.
        /// </summary>
        public static string DiagnoseImage {
            get {
                return ResourceManager.GetString("DiagnoseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Details.
        /// </summary>
        public static string Diagnosis_Details {
            get {
                return ResourceManager.GetString("Diagnosis_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Form.
        /// </summary>
        public static string Diagnosis_Form {
            get {
                return ResourceManager.GetString("Diagnosis_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Result.
        /// </summary>
        public static string DiagnosisResult {
            get {
                return ResourceManager.GetString("DiagnosisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Preview.
        /// </summary>
        public static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the image.
        /// </summary>
        public static string ImageUploadError {
            get {
                return ResourceManager.GetString("ImageUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Advice.
        /// </summary>
        public static string MedicalAdvice {
            get {
                return ResourceManager.GetString("MedicalAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence level not available.
        /// </summary>
        public static string NoConfidenceAvailable {
            get {
                return ResourceManager.GetString("NoConfidenceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image uploaded.
        /// </summary>
        public static string NoImageUploaded {
            get {
                return ResourceManager.GetString("NoImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symptoms selected.
        /// </summary>
        public static string NoSymptoms {
            get {
                return ResourceManager.GetString("NoSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Level.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Description.
        /// </summary>
        public static string RequestDescription {
            get {
                return ResourceManager.GetString("RequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Diagnosis.
        /// </summary>
        public static string SaveDiagnosis {
            get {
                return ResourceManager.GetString("SaveDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        public static string SelectImageAlert {
            get {
                return ResourceManager.GetString("SelectImageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select symptoms....
        /// </summary>
        public static string SelectSymptoms {
            get {
                return ResourceManager.GetString("SelectSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms.
        /// </summary>
        public static string Symptoms {
            get {
                return ResourceManager.GetString("Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diagnosis.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Image.
        /// </summary>
        public static string UploadedImage {
            get {
                return ResourceManager.GetString("UploadedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Radiology Image:.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
    }
}
