//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediAI.Resources.SystemLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediAI.Resources.SystemLog.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string Create_New_User {
            get {
                return ResourceManager.GetString("Create_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string Delete_User {
            get {
                return ResourceManager.GetString("Delete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case accepted for review.
        /// </summary>
        public static string Diagnosis_Accepted {
            get {
                return ResourceManager.GetString("Diagnosis_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis completed and report sent.
        /// </summary>
        public static string Diagnosis_Completed {
            get {
                return ResourceManager.GetString("Diagnosis_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis created manually.
        /// </summary>
        public static string Diagnosis_Created {
            get {
                return ResourceManager.GetString("Diagnosis_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis deleted.
        /// </summary>
        public static string Diagnosis_Deleted {
            get {
                return ResourceManager.GetString("Diagnosis_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis data updated.
        /// </summary>
        public static string Diagnosis_Edited {
            get {
                return ResourceManager.GetString("Diagnosis_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis predicted by AI.
        /// </summary>
        public static string Diagnosis_Predicted_AI {
            get {
                return ResourceManager.GetString("Diagnosis_Predicted_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis reviewed.
        /// </summary>
        public static string Diagnosis_Reviewed {
            get {
                return ResourceManager.GetString("Diagnosis_Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New doctor added.
        /// </summary>
        public static string Doctor_Added {
            get {
                return ResourceManager.GetString("Doctor_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor deleted.
        /// </summary>
        public static string Doctor_Deleted {
            get {
                return ResourceManager.GetString("Doctor_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor information updated.
        /// </summary>
        public static string Doctor_Updated {
            get {
                return ResourceManager.GetString("Doctor_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string Edit_User {
            get {
                return ResourceManager.GetString("Edit_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found.
        /// </summary>
        public static string NoLogsFound {
            get {
                return ResourceManager.GetString("NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical report generated.
        /// </summary>
        public static string Report_Generated {
            get {
                return ResourceManager.GetString("Report_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New symptom created.
        /// </summary>
        public static string Symptom_Created {
            get {
                return ResourceManager.GetString("Symptom_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom deleted.
        /// </summary>
        public static string Symptom_Deleted {
            get {
                return ResourceManager.GetString("Symptom_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom details viewed.
        /// </summary>
        public static string Symptom_Details_Viewed {
            get {
                return ResourceManager.GetString("Symptom_Details_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom updated.
        /// </summary>
        public static string Symptom_Updated {
            get {
                return ResourceManager.GetString("Symptom_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms API accessed.
        /// </summary>
        public static string Symptoms_List_Api {
            get {
                return ResourceManager.GetString("Symptoms_List_Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms list viewed.
        /// </summary>
        public static string Symptoms_List_Viewed {
            get {
                return ResourceManager.GetString("Symptoms_List_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        public static string SystemLog {
            get {
                return ResourceManager.GetString("SystemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        public static string SystemLogs {
            get {
                return ResourceManager.GetString("SystemLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created.
        /// </summary>
        public static string User_Created {
            get {
                return ResourceManager.GetString("User_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the user.
        /// </summary>
        public static string User_Creation_Error {
            get {
                return ResourceManager.GetString("User_Creation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted.
        /// </summary>
        public static string User_Deleted {
            get {
                return ResourceManager.GetString("User_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        public static string User_Deleted_Success {
            get {
                return ResourceManager.GetString("User_Deleted_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in.
        /// </summary>
        public static string User_Login {
            get {
                return ResourceManager.GetString("User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered.
        /// </summary>
        public static string User_Registered {
            get {
                return ResourceManager.GetString("User_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        public static string User_Updated {
            get {
                return ResourceManager.GetString("User_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
